--- @alias jumpDest 'start' | 'end' | 'top' | 'bottom' | 'origin'
--- @alias operatorOpts { jump:jumpDest? }
--- @alias operatorPositions { top:integer, bottom:integer, start:integer, end:integer }
--- @alias visualOpts { jump:'top'|'bottom'|'origin'?, resume_visual:boolean? }
--- @alias position [integer, integer]
--- @alias selectionType 'char' | 'line' | 'block
--- @alias visualRange { top:position, bottom:position, selection_type:selectionType }
